import type { VerifyBusinessResult, VerifyOwnerResult } from './types'

/** Figma 디자인 기준 목업 데이터 */
export const MOCK_VERIFY_RESULT: VerifyBusinessResult = {
  company: {
    name: '모튼 인테리어',
    registrationNumber: '000-00-00000',
  },
  checkItems: [
    {
      id: 'BUSINESS_STATUS',
      category: 'BUSINESS_LICENSE',
      label: '사업자 상태',
      source: '국세청',
      status: '정상 운영',
      statusType: 'positive',
      description: '국세청 기준 현재 영업 상태를 확인해요.',
      details: [
        { key: '사업자등록번호', value: '000-00-00000' },
        { key: '납세자상태', value: '계속사업자' },
        { key: '과세유형', value: '일반과세자' },
      ],
    },
    {
      id: 'CONSTRUCTION_LICENSE',
      category: 'BUSINESS_LICENSE',
      label: '건설업 면허',
      source: '국토교통부',
      status: '확인',
      statusType: 'positive',
      description: '국토교통부에 등록된 건설업 면허 등록 현황이에요.',
      details: [
        { key: '소재지', value: '경기도 수원시 장안구 율전로 64번길 41-11' },
        { key: '등록일자', value: '0000.00.00' },
        { key: '업체명', value: '모튼타일' },
        { key: '업체대표자명', value: '이송목' },
        { key: '등록업종', value: '타일' },
        { key: '업종등록번호', value: '경기수원 0000' },
        { key: '사업자등록번호', value: '000-00-00000' },
        { key: '전화번호', value: '010-0000-0000' },
      ],
    },
    {
      id: 'SPECIALTY_LICENSE',
      category: 'BUSINESS_LICENSE',
      label: '전문건설업 면허',
      source: '대한전문건설협회',
      status: '확인',
      statusType: 'positive',
      description: '대한전문건설협회에 등록된 전문건설업 면허 등록 현황이에요.',
      details: [
        { key: '업체명', value: '모튼타일' },
        { key: '대표자', value: '이송목' },
        { key: '등록업종', value: '타일·방수·조적' },
        { key: '소재지', value: '경기도 수원시' },
      ],
    },
    {
      id: 'ELECTRICAL_LICENSE',
      category: 'BUSINESS_LICENSE',
      label: '전기공사업 면허',
      source: '한국전기공사협회',
      status: '미확인',
      statusType: 'neutral',
      description: '한국전기공사협회 기준 전기공사업 면허 등록 현황이에요.',
      details: [],
    },
    {
      id: 'FIRE_LICENSE',
      category: 'BUSINESS_LICENSE',
      label: '소방시설업 면허',
      source: '한국소방시설협회',
      status: '미확인',
      statusType: 'neutral',
      description: '한국소방공사협회 기준 소방시설업 면허 등록 현황이에요.',
      details: [],
    },
    {
      id: 'WAGE_ARREARS',
      category: 'WAGE_RESTRICTION',
      label: '임금체불 이력',
      source: '고용노동부',
      status: '해당 없음',
      statusType: 'positive',
      description: '고용노동부 공표 체불사업주 명단이에요.',
      details: [],
    },
    {
      id: 'HABITUAL_ARREARS',
      category: 'WAGE_RESTRICTION',
      label: '상습체불 이력',
      source: '국토교통부',
      status: '해당 없음',
      statusType: 'positive',
      description: '국토교통부 공표 상습체불 명단이에요.',
      details: [],
    },
    {
      id: 'SUBCONTRACT_RESTRICTION',
      category: 'WAGE_RESTRICTION',
      label: '하도급 참여제한',
      source: '국토교통부',
      status: '해당 없음',
      statusType: 'positive',
      description: '국토교통부 공표 하도급법 위반 제재 명단을 확인해요.',
      details: [],
    },
    {
      id: 'RETIREMENT_FUND',
      category: 'INSURANCE',
      label: '퇴직공제 가입 공사 이력',
      source: '건설근로자공제회',
      status: '3건 조회',
      statusType: 'positive',
      description: '건설근로자공제회에 등록된 퇴직공제 가입 공사 이력이에요.',
      details: [
        { key: '공사명', value: 'OO아파트 신축공사' },
        { key: '총공사금액', value: '50,000,000원' },
        { key: '공사기간', value: '2024.01 ~ 2024.06' },
      ],
    },
    {
      id: 'EMPLOYMENT_INSURANCE',
      category: 'INSURANCE',
      label: '고용/산재보험 현황',
      source: '근로복지공단',
      status: '확인',
      statusType: 'positive',
      description: '근로복지공단에 등록된 보험 가입 현황이에요.',
      details: [
        { key: '고용보험', value: '가입' },
        { key: '산재보험', value: '가입' },
        { key: '사업장관리번호', value: '000-00-00000-0' },
      ],
    },
  ],
}

/** 진위확인 목업 응답 */
export const MOCK_VERIFY_OWNER_RESULT: VerifyOwnerResult = {
  valid: true,
  message: '사업자등록번호와 대표자명, 개업일자가 일치합니다.',
}
