career:
  - 'apps/career/**'
  - 'packages/ui/**'
  - 'packages/config/**'
  - 'packages/mocks/**'
  - 'packages/api-client/src/*.ts'
  - 'packages/api-client/orval.*.ts'
  - 'packages/api-client/package.json'
  - 'packages/api-client/tsconfig.json'
  - 'package.json'
  - 'pnpm-lock.yaml'
plan:
  - 'apps/plan/**'
  - 'packages/ui/**'
  - 'packages/config/**'
  - 'packages/mocks/**'
  - 'packages/api-client/src/*.ts'
  - 'packages/api-client/orval.*.ts'
  - 'packages/api-client/package.json'
  - 'packages/api-client/tsconfig.json'
  - 'package.json'
  - 'pnpm-lock.yaml'
fe:
  - 'apps/career/**'
  - 'apps/plan/**'
  - 'packages/ui/**'
  - 'packages/config/**'
  - 'packages/mocks/**'
  - 'packages/api-client/src/*.ts'
  - 'packages/api-client/orval.*.ts'
  - 'packages/api-client/package.json'
  - 'packages/api-client/tsconfig.json'
  - 'package.json'
  - 'pnpm-lock.yaml'
api:
  - 'apps/api/**'
api-spec:
  - 'apps/api/**'
crawler:
  - 'apps/crawler/**'
packages:
  - '**/package.json'
  - 'pnpm-workspace.yaml'
  - 'pnpm-lock.yaml'
  - '.syncpackrc.json'
  - 'packages/ui/**'
  - 'packages/config/eslint/**'
