# lychee 설정

# 환경 변수 : {GITHUB_TOKEN}

# 검사 대상
include_verbatim = true # 코드 블록 내부 포함
include_mail = false
exclude_path = ["node_modules"]

# 동작
max_concurrency = 32        # 부하 절감

# 캐싱
cache = true

# 출력
no_progress = true
verbose = "warn"
