plugins {
    id 'org.springframework.boot'
    id 'io.sentry.jvm.gradle' version '6.1.0'
}

sentry {
    includeSourceContext = System.getenv("SENTRY_AUTH_TOKEN") != null
    org = "morton-2l"
    projectName = "api"
    authToken = System.getenv("SENTRY_AUTH_TOKEN")
}

bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation project(':support')
    implementation project(':storage')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // TODO: socketio
    // implementation 'com.corundumstudio.socketio:netty-socketio:2.0.12'

    // db
    implementation 'org.springframework.boot:spring-boot-h2console'

    // TODO: aws
    // implementation 'software.amazon.awssdk:s3:2.42.0'
    // implementation platform('io.awspring.cloud:spring-cloud-aws-dependencies:4.0.0')
    // implementation 'io.awspring.cloud:spring-cloud-aws-starter'
    // implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'

    // jwt
    implementation("io.jsonwebtoken:jjwt-api:0.13.0")
    runtimeOnly ("io.jsonwebtoken:jjwt-impl:0.13.0")
    runtimeOnly("io.jsonwebtoken:jjwt-orgjson:0.13.0")

    // sms
    implementation 'net.nurigo:sdk:4.3.0'

    // monitor
    implementation 'io.micrometer:micrometer-core'
    implementation 'io.sentry:sentry-spring-boot-4:8.34.1'

    // test
    testImplementation "org.testcontainers:testcontainers"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter"
    testImplementation "org.testcontainers:testcontainers-postgresql"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
}
