spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///test

  sql:
    init:
      schema-locations:
        - classpath:schema-postgresql.sql
        - classpath:schema-crawler-postgresql.sql

app:
  jwt:
    secret: test-secret-key-for-jwt-authentication-minimum-256-bits

  sms:
    api-key: test-api-key
    api-secret: test-api-secret
    sender-number: "01000000000"

  s3:
    bucket: test-bucket

  cloudfront:
    key-pair-id: test-key-pair-id
    private-key: test-private-key