spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema-prod.sql

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: ${SENTRY_ENVIRONMENT}

app:
  sms:
    api-key: ${SOLAPI_API_KEY}
    api-secret: ${SOLAPI_API_SECRET}
    sender-number: ${SOLAPI_SENDER_NUMBER}
