spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      data-locations: classpath:data-prod.sql
      schema-locations:
        - classpath:schema-postgresql.sql

sentry:
  dsn: ${SENTRY_DSN:}
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: ${SENTRY_ENVIRONMENT:prod}

app:
  jwt:
    cookie-domain: ${COOKIE_DOMAIN:.bconnect.to}