spring:
  datasource:
    url: jdbc:h2:mem:db;mode=postgresql;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2
      data-locations:
        - classpath:data.sql
        - classpath:data-crawler.sql

app:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-origin-patterns:
    - "http://localhost:[*]"
    - "http://127.0.0.1:[*]"

  jwt:
    secret: local-secret-key-for-jwt-authentication-minimum-256-bits
    cookie-domain: localhost

  data-go:
    service-key: local-service-key

  s3:
    region: local-region
    bucket: local-bucket

  cloudfront:
    key-pair-id: local-key-pair-id
    private-key: local-private-key

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.messaging.simp.stomp: TRACE
