spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///test

  sql:
    init:
      schema-locations:
        - classpath:schema-postgresql.sql
      data-locations:
        - classpath:data.sql
        - classpath:data-crawler.sql

app:
  jwt:
    secret: test-secret-key-for-jwt-authentication-minimum-256-bits
    cookie-domain: localhost

  data-go:
    service-key: test-service-key

  s3:
    bucket: test-bucket

  cloudfront:
    key-pair-id: test-key-pair-id
    private-key: test-private-key

  sns:
    platform-application-arn: test-sns-arn