-- 운영 데이터 (0 ~ 99)
-- 실제 데이터 (1000 ~)

-- 운영 데이터 (0 ~ 99)
INSERT INTO members (id, username, name, phone, created_at, modified_at) VALUES
(0, 'system', '시스템', '01000000000', now(), now()),
(1, 'admin', '관리자', '01083358632', now(), now());

INSERT INTO member_roles (member_id, role) VALUES
(0, 'ADMIN'),
(1, 'ADMIN');

-- 실제 데이터 (1000 ~)
ALTER TABLE otps ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE signup_tokens ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE members ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE sessions ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE group_chats ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE direct_chats ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE participants ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE messages ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE profiles ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE tasks ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE offers ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE companies ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE projects ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE posts ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE credentials ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE attachments ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE coworkers ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE coworker_requests ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE recommendations ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE drives ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE drive_members ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE boards ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE notes ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE crawled_members ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE crawled_profiles ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE crawled_tasks ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE crawled_posts ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE crawled_credentials ALTER COLUMN id RESTART WITH 1000;