-- prod 스키마 (직접 실행)

create table if not exists otps (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    code varchar(255) not null,
    expired_at timestamptz not null,
    attempts integer not null,
    revoked boolean not null,
    daily_count integer not null,
    last_sent_at timestamptz not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists signup_tokens (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    token varchar(255) not null,
    expired_at timestamptz not null,
    revoked boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_signup_tokens_phone on signup_tokens(phone) where deleted_at is null;

create table if not exists members (
    id bigint generated by default as identity,
    username varchar(255) not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_members_username on members(username) where deleted_at is null;
create unique index if not exists udx_members_phone on members(phone) where deleted_at is null;

create table if not exists member_roles (
    member_id bigint not null references members(id),
    role varchar(255)
);

create table if not exists sessions (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_sessions_member on sessions(member_id) where deleted_at is null;

create table if not exists attachments (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    context varchar(255) not null,
    context_id bigint not null,
    reference_type varchar(255),
    reference_id bigint,
    uuid varchar(255) not null,
    stem varchar(255) not null,
    ext varchar(255) not null,
    content_type varchar(255) not null,
    size bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_attachments_uuid on attachments(uuid) where deleted_at is null;

create table if not exists group_chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists direct_chats (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    min_last_idx bigint not null,
    max_last_idx bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_direct_chats_members on direct_chats(min_id, max_id) where deleted_at is null;

create table if not exists participants (
    id bigint generated by default as identity,
    chat_id bigint not null references group_chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    chat_type varchar(255) not null,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    content TEXT not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists profiles (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    role varchar(255) not null,
    primary_trade varchar(255) not null,
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_profiles_member on profiles(member_id) where deleted_at is null;

create table if not exists profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255)
);

create table if not exists companies (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    name varchar(255) not null,
    brn varchar(255) not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_companies_member on companies(member_id) where deleted_at is null;
create unique index if not exists udx_companies_brn on companies(brn) where deleted_at is null;

create table if not exists projects (
    id bigint generated by default as identity,
    company_id bigint not null references companies(id),
    title varchar(255) not null,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists tasks (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    status varchar(255) not null,
    start_date date not null,
    end_date date not null,
    worker_id bigint references members(id),
    worker_title varchar(255),
    worker_memo varchar(255),
    worker_company varchar(255),
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    project_id bigint references projects(id),
    project_title varchar(255),
    project_requirement varchar(255),
    project_memo varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255)
);

create table if not exists offers (
    id bigint generated by default as identity,
    task_id bigint not null references tasks(id),
    worker_id bigint not null references members(id),
    seq integer not null,
    due date,
    status varchar(255) not null,
    version bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists posts (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists credentials (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    expired_at date,
    note TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists coworkers (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_coworkers_members on coworkers(min_id, max_id) where deleted_at is null;

create table if not exists coworker_requests (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_coworker_requests_members on coworker_requests(from_id, to_id) where deleted_at is null;

create table if not exists recommendations (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    content TEXT not null,
    visible boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_recommendations_from_to on recommendations(from_id, to_id) where deleted_at is null;

create table if not exists drives (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    member_id bigint references members(id),
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists drive_members (
    id bigint generated by default as identity,
    drive_id bigint not null references drives(id),
    member_id bigint not null references members(id),
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists boards (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    drive_id bigint references drives(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists notes (
    id bigint generated by default as identity,
    board_id bigint not null references boards(id),
    member_id bigint not null references members(id),
    content TEXT not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists crawled_members (
    id bigint generated by default as identity,
    company varchar(255) not null,
    name varchar(255),
    phone varchar(255),
    picture TEXT,
    role varchar(255) not null,
    brn varchar(255),
    email varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists crawled_profiles (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    primary_trade varchar(255),
    experience integer,
    headline varchar(255),
    address varchar(255),
    state varchar(255),
    url varchar(255) not null,
    platform varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index if not exists udx_crawled_profiles_member on crawled_profiles(member_id) where deleted_at is null;
create unique index if not exists udx_crawled_profiles_url on crawled_profiles(url) where deleted_at is null;

create table if not exists crawled_profile_trades (
    profile_id bigint not null references crawled_profiles(id),
    trade varchar(255)
);

create table if not exists crawled_tasks (
    id bigint generated by default as identity,
    company varchar(255),
    address varchar(255),
    trade varchar(255),
    start_date date,
    end_date date,
    duration varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists crawled_posts (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    task_id bigint references crawled_tasks(id),
    title varchar(255),
    content TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists crawled_post_images (
    post_id bigint not null references crawled_posts(id),
    seq integer not null,
    url TEXT
);

create table if not exists crawled_credentials (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    type varchar(255) not null,
    name varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists device_tokens (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    token varchar(1024) not null unique,
    platform varchar(255) not null,
    sns_endpoint_arn varchar(512) not null,
    enabled boolean not null,
    last_active_at timestamptz not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    primary key (id)
);

create table if not exists notifications (
    id bigint generated by default as identity,
    sender_id bigint references members(id),
    receiver_id bigint not null references members(id),
    type_code varchar(255) not null,
    reference_id bigint,
    content text,
    template_args text,
    read_at timestamptz,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table if not exists kiscon_registration (
    ncr_gs_seq bigint,
    biz_reg_no text not null,
    company_name text,
    representative text,
    trade_name text,
    trade_reg_no text,
    address text,
    region text,
    region_detail text,
    reg_date integer,
    announce_date integer,
    flag text,
    phone text,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_reg_biz_no on kiscon_registration(biz_reg_no);

create table if not exists kiscon_admin_penalty (
    ncr_gs_seq bigint,
    biz_reg_no text not null,
    company_name text,
    representative text,
    trade_name text,
    trade_reg_no text,
    address text,
    region text,
    region_detail text,
    penalty_type text,
    violation_content text,
    violation_detail text,
    penalty_ground text,
    fine_amount bigint default 0,
    penalty_amount bigint default 0,
    stop_start_date text,
    stop_end_date text,
    cancel_date text,
    correction text,
    penalty_date integer,
    announce_date integer,
    flag text,
    phone text,
    has_injunction text,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_admi_biz_no on kiscon_admin_penalty(biz_reg_no);

create table if not exists kiscon_arrears (
    id bigint generated by default as identity,
    company_name text not null,
    address text,
    representative text,
    penalty_history text,
    arrears_amount text,
    publication_period text,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table if not exists kiscon_subcon_limits (
    id bigint generated by default as identity,
    violation_type text,
    company_name text not null,
    corp_no text,
    biz_reg_no text not null,
    representative text,
    restriction_start text,
    restriction_end text,
    category text,
    announcement_date text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
create index if not exists idx_kiscon_subcon_biz_no on kiscon_subcon_limits(biz_reg_no);

create table if not exists moel_wage_defaults (
    id bigint generated by default as identity,
    period text,
    name text,
    age text,
    company_name text,
    industry text,
    personal_address text,
    company_address text,
    arrears_amount text,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table if not exists ecic_electrical_licenses (
    id bigint generated by default as identity,
    registration_no text,
    company_name text,
    representative text,
    address text,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table if not exists cwma_retirement_fund (
    id bigint generated by default as identity,
    project_name text,
    total_amount numeric,
    start_date date,
    end_date date,
    company_name text,
    normalized_company_name text,
    client_org text,
    address text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
create index if not exists idx_cwma_normalized_name on cwma_retirement_fund(normalized_company_name);

create table if not exists feia_fire_licenses (
    id bigint generated by default as identity,
    company_name text,
    ceo_name text,
    address text,
    license_name text,
    license_div text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
