drop table if exists notes cascade;
drop table if exists boards cascade;
drop table if exists drive_members cascade;
drop table if exists drives cascade;
drop table if exists messages cascade;
drop table if exists participants cascade;
drop table if exists direct_chats cascade;
drop table if exists group_chats cascade;
drop table if exists recommendations cascade;
drop table if exists coworker_requests cascade;
drop table if exists coworkers cascade;
drop table if exists credentials cascade;
drop table if exists offers cascade;
drop table if exists task_trades cascade;
drop table if exists tasks cascade;
drop table if exists projects cascade;
drop table if exists companies cascade;
drop table if exists profile_trades cascade;
drop table if exists profiles cascade;
drop table if exists posts cascade;
drop table if exists attachments cascade;
drop table if exists sessions cascade;
drop table if exists members cascade;
drop table if exists otps cascade;

create table otps (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    code varchar(255) not null,
    code_expired_at timestamp(6) not null,
    attempts integer not null,
    code_revoked boolean not null,
    token varchar(255),
    token_expired_at timestamp(6),
    token_revoked boolean,
    daily_count integer not null,
    last_sent_at timestamp(6) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table members (
    id bigint generated by default as identity,
    username varchar(255) not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    role varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_members_username on members(username) where deleted_at is null;
create unique index udx_members_phone on members(phone) where deleted_at is null;

create table sessions (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_sessions_member on sessions(member_id) where deleted_at is null;

create table attachments (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    context varchar(255) not null,
    context_id bigint not null,
    reference_type varchar(255),
    reference_id bigint,
    uuid varchar(255) not null,
    stem varchar(255) not null,
    ext varchar(255) not null,
    content_type varchar(255) not null,
    size bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_attachments_uuid on attachments(uuid) where deleted_at is null;

create table group_chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table direct_chats (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    min_last_idx bigint not null,
    max_last_idx bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_direct_chats_members on direct_chats(min_id, max_id) where deleted_at is null;

create table participants (
    id bigint generated by default as identity,
    chat_id bigint not null references group_chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    chat_type varchar(255) not null,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    content TEXT not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    role varchar(255) not null,
    primary_trade varchar(255) not null,
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_profiles_member on profiles(member_id) where deleted_at is null;

create table profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255)
);

create table companies (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    name varchar(255) not null,
    brn varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_companies_member on companies(member_id) where deleted_at is null;
create unique index udx_companies_brn on companies(brn) where deleted_at is null;

create table projects (
    id bigint generated by default as identity,
    company_id bigint not null references companies(id),
    title varchar(255) not null,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table tasks (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    status varchar(255) not null,
    start_date date not null,
    end_date date not null,
    worker_id bigint references members(id),
    worker_title varchar(255),
    worker_memo varchar(255),
    worker_company varchar(255),
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    project_id bigint references projects(id),
    project_title varchar(255),
    project_requirement varchar(255),
    project_memo varchar(255),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255)
);

create table offers (
    id bigint generated by default as identity,
    task_id bigint not null references tasks(id),
    worker_id bigint not null references members(id),
    seq integer not null,
    due date not null,
    status varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table posts (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table credentials (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    expired_at date,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table coworkers (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_coworkers_members on coworkers(min_id, max_id) where deleted_at is null;

create table coworker_requests (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_coworker_requests_members on coworker_requests(from_id, to_id) where deleted_at is null;

create table recommendations (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    content TEXT not null,
    visible boolean not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
create unique index udx_recommendations_from_to on recommendations(from_id, to_id) where deleted_at is null;

create table drives (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    member_id bigint references members(id),
    title varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table drive_members (
    id bigint generated by default as identity,
    drive_id bigint not null references drives(id),
    member_id bigint not null references members(id),
    title varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table boards (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    drive_id bigint references drives(id),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table notes (
    id bigint generated by default as identity,
    board_id bigint not null references boards(id),
    member_id bigint not null references members(id),
    content TEXT,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
