create table if not exists kiscon_registration (
    ncr_gs_seq bigint,
    biz_reg_no TEXT not null,
    company_name TEXT,
    representative TEXT,
    trade_name TEXT,
    trade_reg_no TEXT,
    address TEXT,
    region TEXT,
    region_detail TEXT,
    reg_date integer,
    announce_date integer,
    flag TEXT,
    phone TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_reg_biz_no on kiscon_registration(biz_reg_no);

create table if not exists kiscon_admin_penalty (
    ncr_gs_seq bigint,
    biz_reg_no TEXT not null,
    company_name TEXT,
    representative TEXT,
    trade_name TEXT,
    trade_reg_no TEXT,
    address TEXT,
    region TEXT,
    region_detail TEXT,
    penalty_type TEXT,
    violation_content TEXT,
    violation_detail TEXT,
    penalty_ground TEXT,
    fine_amount bigint default 0,
    penalty_amount bigint default 0,
    stop_start_date TEXT,
    stop_end_date TEXT,
    cancel_date TEXT,
    correction TEXT,
    penalty_date integer,
    announce_date integer,
    flag TEXT,
    phone TEXT,
    has_injunction TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_admi_biz_no on kiscon_admin_penalty(biz_reg_no);

create table if not exists kiscon_arrears (
    id bigint generated by default as identity,
    company_name TEXT not null,
    address TEXT,
    representative TEXT,
    penalty_history TEXT,
    arrears_amount TEXT,
    publication_period TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);

create table if not exists kiscon_subcon_limits (
    id bigint generated by default as identity,
    violation_type TEXT,
    company_name TEXT not null,
    corp_no TEXT,
    biz_reg_no TEXT not null,
    representative TEXT,
    restriction_start TEXT,
    restriction_end TEXT,
    category TEXT,
    announcement_date TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_kiscon_subcon_biz_no on kiscon_subcon_limits(biz_reg_no);

create table if not exists moel_wage_defaults (
    id bigint generated by default as identity,
    period TEXT,
    name TEXT,
    age TEXT,
    company_name TEXT,
    industry TEXT,
    personal_address TEXT,
    company_address TEXT,
    arrears_amount TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);

create table if not exists ecic_electrical_licenses (
    id bigint generated by default as identity,
    registration_no TEXT,
    company_name TEXT,
    representative TEXT,
    address TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);

create table if not exists cwma_retirement_fund (
    id bigint generated by default as identity,
    project_name TEXT,
    total_amount numeric,
    start_date date,
    end_date date,
    company_name TEXT,
    normalized_company_name TEXT,
    client_org TEXT,
    address TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_cwma_normalized_name on cwma_retirement_fund(normalized_company_name);

create table if not exists feia_fire_licenses (
    id bigint generated by default as identity,
    company_name TEXT,
    ceo_name TEXT,
    address TEXT,
    license_name TEXT,
    license_div TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);
