drop table if exists coworker_requests cascade;
drop table if exists coworkers cascade;
drop table if exists credentials cascade;
drop table if exists recommendations cascade;
drop table if exists post_images cascade;
drop table if exists posts cascade;
drop table if exists task_trades cascade;
drop table if exists tasks cascade;
drop table if exists projects cascade;
drop table if exists companies cascade;
drop table if exists profile_trades cascade;
drop table if exists profiles cascade;
drop table if exists messages cascade;
drop table if exists participants cascade;
drop table if exists direct_chats cascade;
drop table if exists group_chats cascade;
drop table if exists sessions cascade;
drop table if exists members cascade;
drop table if exists otps cascade;

create table otps (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    code varchar(255) not null,
    code_expired_at timestamp(6) not null,
    code_revoked boolean not null,
    attempts integer not null,
    daily_count integer not null,
    last_sent_at timestamp(6) not null,
    token varchar(255),
    token_expired_at timestamp(6),
    token_revoked boolean,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table members (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    name varchar(255) not null,
    phone varchar(255) not null unique,
    picture varchar(255),
    role varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table sessions (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table group_chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table direct_chats (
    id bigint generated by default as identity,
    min_id bigint not null,
    max_id bigint not null,
    min_last_idx bigint not null,
    max_last_idx bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id),
    unique (min_id, max_id)
);

create table participants (
    id bigint generated by default as identity,
    chat_id bigint not null references group_chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    chat_type varchar(255) not null,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    content TEXT not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    member_id bigint not null unique references members(id),
    primary_trade varchar(255) not null,
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    picture_id bigint references attachments(id),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255)
);

create table companies (
    id bigint generated by default as identity,
    member_id bigint not null unique references members(id),
    name varchar(255) not null,
    brn varchar(255) not null,
    picture varchar(255),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table projects (
    id bigint generated by default as identity,
    company_id bigint not null references companies(id),
    title varchar(255) not null,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table tasks (
    id bigint generated by default as identity,
    dtype varchar(31) not null,
    status varchar(255) not null,
    start_date date not null,
    end_date date not null,
    worker_id bigint references members(id),
    worker_title varchar(255),
    worker_memo varchar(255),
    worker_company varchar(255),
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    project_id bigint references projects(id),
    project_title varchar(255),
    project_requirement varchar(255),
    project_memo varchar(255),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255)
);

create table posts (
    id bigint generated by default as identity,
    member_id bigint references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table post_images (
    post_id bigint not null references posts(id),
    images varchar(255)
);

create table credentials (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    expired_at date,
    attachment_id bigint references attachments(id),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);

create table coworkers (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    primary key (id),
    constraint uk_coworkers_min_max unique (min_id, max_id)
);

create table coworker_requests (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    primary key (id),
    constraint uk_coworker_requests_from_to unique (from_id, to_id)
);

create table recommendations (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    content TEXT not null,
    visible boolean not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted_at timestamp,
    primary key (id)
);
