-- partial unique index 미포함

drop table if exists notes cascade;
drop table if exists boards cascade;
drop table if exists drive_members cascade;
drop table if exists drives cascade;
drop table if exists messages cascade;
drop table if exists participants cascade;
drop table if exists direct_chats cascade;
drop table if exists group_chats cascade;
drop table if exists recommendations cascade;
drop table if exists coworker_requests cascade;
drop table if exists coworkers cascade;
drop table if exists credentials cascade;
drop table if exists offers cascade;
drop table if exists task_trades cascade;
drop table if exists tasks cascade;
drop table if exists projects cascade;
drop table if exists companies cascade;
drop table if exists profile_trades cascade;
drop table if exists profiles cascade;
drop table if exists posts cascade;
drop table if exists attachments cascade;
drop table if exists sessions cascade;
drop table if exists notifications cascade;
drop table if exists device_tokens cascade;
drop table if exists members cascade;
drop table if exists signup_tokens cascade;
drop table if exists otps cascade;
drop table if exists crawled_credentials cascade;
drop table if exists crawled_post_images cascade;
drop table if exists crawled_posts cascade;
drop table if exists crawled_tasks cascade;
drop table if exists crawled_profile_trades cascade;
drop table if exists crawled_profiles cascade;
drop table if exists crawled_members cascade;
drop table if exists kiscon_admin_penalty cascade;
drop table if exists kiscon_registration cascade;

create table otps (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    code varchar(255) not null,
    expired_at timestamp(6) with time zone not null,
    attempts integer not null,
    revoked boolean not null,
    daily_count integer not null,
    last_sent_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table signup_tokens (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    token varchar(255) not null,
    expired_at timestamp(6) with time zone not null,
    revoked boolean not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_signup_tokens_phone on signup_tokens(phone);

create table members (
    id bigint generated by default as identity,
    username varchar(255) not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    role varchar(255) not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_members_username on members(username);
create index udx_members_phone on members(phone);

create table device_tokens (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    token varchar(1024) not null unique,
    platform varchar(255) not null,
    sns_endpoint_arn varchar(512) not null,
    enabled boolean not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    primary key (id)
);

create table notifications (
    id bigint generated by default as identity,
    sender_id bigint references members(id),
    receiver_id bigint not null references members(id),
    type_code varchar(255) not null,
    reference_id bigint,
    content text,
    template_args text,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table sessions (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_sessions_member on sessions(member_id);

create table attachments (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    context varchar(255) not null,
    context_id bigint not null,
    reference_type varchar(255),
    reference_id bigint,
    uuid varchar(255) not null,
    stem varchar(255) not null,
    ext varchar(255) not null,
    content_type varchar(255) not null,
    size bigint not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_attachments_uuid on attachments(uuid);

create table group_chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table direct_chats (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    min_last_idx bigint not null,
    max_last_idx bigint not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_direct_chats_members on direct_chats(min_id, max_id);

create table participants (
    id bigint generated by default as identity,
    chat_id bigint not null references group_chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    chat_type varchar(255) not null,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    content TEXT not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    role varchar(255) not null,
    primary_trade varchar(255) not null,
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_profiles_member on profiles(member_id);

create table profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255)
);

create table companies (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    name varchar(255) not null,
    brn varchar(255) not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_companies_member on companies(member_id);
create index udx_companies_brn on companies(brn);

create table projects (
    id bigint generated by default as identity,
    company_id bigint not null references companies(id),
    title varchar(255) not null,
    zipcode varchar(5) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table tasks (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    status varchar(255) not null,
    start_date date not null,
    end_date date not null,
    worker_id bigint references members(id),
    worker_title varchar(255),
    worker_memo varchar(255),
    worker_company varchar(255),
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    project_id bigint references projects(id),
    project_title varchar(255),
    project_requirement varchar(255),
    project_memo varchar(255),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255)
);

create table offers (
    id bigint generated by default as identity,
    task_id bigint not null references tasks(id),
    worker_id bigint not null references members(id),
    seq integer not null,
    due date,
    status varchar(255) not null,
    version bigint not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table posts (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table credentials (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    expired_at date,
    note TEXT,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table coworkers (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_coworkers_members on coworkers(min_id, max_id);

create table coworker_requests (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_coworker_requests_members on coworker_requests(from_id, to_id);

create table recommendations (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    content TEXT not null,
    visible boolean not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_recommendations_from_to on recommendations(from_id, to_id);

create table drives (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    member_id bigint references members(id),
    title varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table drive_members (
    id bigint generated by default as identity,
    drive_id bigint not null references drives(id),
    member_id bigint not null references members(id),
    title varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table boards (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    drive_id bigint references drives(id),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table notes (
    id bigint generated by default as identity,
    board_id bigint not null references boards(id),
    member_id bigint not null references members(id),
    content TEXT not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table crawled_members (
    id bigint generated by default as identity,
    company varchar(255) not null,
    name varchar(255),
    phone varchar(255),
    picture TEXT,
    role varchar(255) not null,
    brn varchar(255),
    email varchar(255),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table crawled_profiles (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    primary_trade varchar(255),
    experience integer,
    headline varchar(255),
    address varchar(255),
    state varchar(255),
    url varchar(255) not null,
    platform varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
create index udx_crawled_profiles_member on crawled_profiles(member_id);
create index udx_crawled_profiles_url on crawled_profiles(url);

create table crawled_profile_trades (
    profile_id bigint not null references crawled_profiles(id),
    trade varchar(255)
);

create table crawled_tasks (
    id bigint generated by default as identity,
    company varchar(255),
    address varchar(255),
    trade varchar(255),
    start_date date,
    end_date date,
    duration varchar(255),
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table crawled_posts (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    task_id bigint references crawled_tasks(id),
    title varchar(255),
    content TEXT,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table crawled_post_images (
    post_id bigint not null references crawled_posts(id),
    seq integer not null,
    url TEXT
);

create table crawled_credentials (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    type varchar(255) not null,
    name varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    modified_at timestamp(6) with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table kiscon_registration (
    ncr_gs_seq bigint,
    biz_reg_no TEXT not null,
    company_name TEXT,
    representative TEXT,
    trade_name TEXT,
    trade_reg_no TEXT,
    address TEXT,
    region TEXT,
    region_detail TEXT,
    reg_date integer,
    announce_date integer,
    flag TEXT,
    phone TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (ncr_gs_seq)
);
create index idx_kiscon_reg_biz_no on kiscon_registration(biz_reg_no);

create table kiscon_admin_penalty (
    ncr_gs_seq bigint,
    biz_reg_no TEXT not null,
    company_name TEXT,
    representative TEXT,
    trade_name TEXT,
    trade_reg_no TEXT,
    address TEXT,
    region TEXT,
    region_detail TEXT,
    penalty_type TEXT,
    violation_content TEXT,
    violation_detail TEXT,
    penalty_ground TEXT,
    fine_amount bigint default 0,
    penalty_amount bigint default 0,
    stop_start_date TEXT,
    stop_end_date TEXT,
    cancel_date TEXT,
    correction TEXT,
    penalty_date integer,
    announce_date integer,
    flag TEXT,
    phone TEXT,
    has_injunction TEXT,
    synced_at timestamp(6) with time zone not null default current_timestamp,
    primary key (ncr_gs_seq)
);
create index idx_kiscon_admi_biz_no on kiscon_admin_penalty(biz_reg_no);
