-- postgreSQL : partial unique index 포함

drop table if exists notifications cascade;
drop table if exists device_tokens cascade;
drop table if exists notes cascade;
drop table if exists boards cascade;
drop table if exists drive_members cascade;
drop table if exists drives cascade;
drop table if exists messages cascade;
drop table if exists participants cascade;
drop table if exists direct_chats cascade;
drop table if exists group_chats cascade;
drop table if exists recommendations cascade;
drop table if exists coworker_requests cascade;
drop table if exists coworkers cascade;
drop table if exists credentials cascade;
drop table if exists offers cascade;
drop table if exists task_trades cascade;
drop table if exists tasks cascade;
drop table if exists projects cascade;
drop table if exists companies cascade;
drop table if exists profile_trades cascade;
drop table if exists profiles cascade;
drop table if exists posts cascade;
drop table if exists attachments cascade;
drop table if exists sessions cascade;
drop table if exists member_roles cascade;
drop table if exists members cascade;
drop table if exists signup_tokens cascade;
drop table if exists otps cascade;
drop table if exists crawled_credentials cascade;
drop table if exists crawled_post_images cascade;
drop table if exists crawled_posts cascade;
drop table if exists crawled_tasks cascade;
drop table if exists crawled_profile_trades cascade;
drop table if exists crawled_profiles cascade;
drop table if exists crawled_members cascade;
drop table if exists feia_fire_licenses cascade;
drop table if exists cwma_retirement_fund cascade;
drop table if exists ecic_electrical_licenses cascade;
drop table if exists moel_wage_defaults cascade;
drop table if exists kiscon_subcon_limits cascade;
drop table if exists kiscon_arrears cascade;
drop table if exists kiscon_admin_penalty cascade;
drop table if exists kiscon_registration cascade;

create table otps (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    code varchar(255) not null,
    expired_at timestamptz not null,
    attempts integer not null,
    revoked boolean not null,
    daily_count integer not null,
    last_sent_at timestamptz not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table signup_tokens (
    id bigint generated by default as identity,
    phone varchar(255) not null,
    token varchar(255) not null,
    expired_at timestamptz not null,
    revoked boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_signup_tokens_phone on signup_tokens(phone) where deleted_at is null;

create table members (
    id bigint generated by default as identity,
    username varchar(255) not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    birth date not null,
    marketing_consent boolean not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_members_username on members(username) where deleted_at is null;
create unique index udx_members_phone on members(phone) where deleted_at is null;

create table member_roles (
    member_id bigint not null references members(id),
    role varchar(255)
);

create table sessions (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_sessions_member on sessions(member_id) where deleted_at is null;

create table attachments (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    context varchar(255) not null,
    context_id bigint not null,
    reference_type varchar(255),
    reference_id bigint,
    uuid varchar(255) not null,
    stem varchar(255) not null,
    ext varchar(255) not null,
    content_type varchar(255) not null,
    size bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_attachments_uuid on attachments(uuid) where deleted_at is null;

create table group_chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table direct_chats (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    min_last_idx bigint not null,
    max_last_idx bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_direct_chats_members on direct_chats(min_id, max_id) where deleted_at is null;

create table participants (
    id bigint generated by default as identity,
    chat_id bigint not null references group_chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    chat_type varchar(255) not null,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    content TEXT not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    role varchar(255) not null,
    primary_trade varchar(255) not null,
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5) not null,
    bcode varchar(10) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_profiles_member on profiles(member_id) where deleted_at is null;

create table profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255)
);

create table companies (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    name varchar(255) not null,
    brn varchar(255) not null,
    status varchar(255) not null,
    drive_used_bytes bigint not null default 0,
    drive_limit_bytes bigint not null default 1073741824,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_companies_member on companies(member_id) where deleted_at is null;
create unique index udx_companies_brn on companies(brn) where deleted_at is null;

create table projects (
    id bigint generated by default as identity,
    company_id bigint not null references companies(id),
    title varchar(255) not null,
    zipcode varchar(5) not null,
    bcode varchar(10) not null,
    city varchar(255) not null,
    state varchar(255) not null,
    street varchar(255) not null,
    detail varchar(255),
    latitude numeric(10,7) not null,
    longitude numeric(10,7) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table tasks (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    status varchar(255) not null,
    progress varchar(255) not null,
    version bigint not null,
    start_date date not null,
    end_date date not null,
    worker_id bigint references members(id),
    worker_title varchar(255),
    worker_memo varchar(255),
    worker_company varchar(255),
    zipcode varchar(5),
    bcode varchar(10),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    project_id bigint references projects(id),
    project_title varchar(255),
    project_requirement varchar(255),
    project_memo varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255)
);

create table offers (
    id bigint generated by default as identity,
    task_id bigint not null references tasks(id),
    worker_id bigint not null references members(id),
    seq integer not null,
    due date,
    status varchar(255) not null,
    version bigint not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table posts (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table credentials (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    status varchar(255) not null,
    expired_at date,
    note TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table coworkers (
    id bigint generated by default as identity,
    min_id bigint not null references members(id),
    max_id bigint not null references members(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_coworkers_members on coworkers(min_id, max_id) where deleted_at is null;

create table coworker_requests (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_coworker_requests_members on coworker_requests(from_id, to_id) where deleted_at is null;

create table recommendations (
    id bigint generated by default as identity,
    from_id bigint not null references members(id),
    to_id bigint not null references members(id),
    content TEXT not null,
    visible boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_recommendations_from_to on recommendations(from_id, to_id) where deleted_at is null;

create table drives (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    member_id bigint references members(id),
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table drive_members (
    id bigint generated by default as identity,
    drive_id bigint not null references drives(id),
    member_id bigint not null references members(id),
    title varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table boards (
    id bigint generated by default as identity,
    dtype varchar(255) not null,
    project_id bigint references projects(id),
    drive_id bigint references drives(id),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table notes (
    id bigint generated by default as identity,
    board_id bigint not null references boards(id),
    member_id bigint not null references members(id),
    content TEXT not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table crawled_members (
    id bigint generated by default as identity,
    company varchar(255) not null,
    name varchar(255),
    phone varchar(255),
    picture TEXT,
    role varchar(255) not null,
    brn varchar(255),
    email varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table crawled_profiles (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    primary_trade varchar(255),
    experience integer,
    headline varchar(255),
    address varchar(255),
    state varchar(255),
    url varchar(255) not null,
    platform varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);
create unique index udx_crawled_profiles_member on crawled_profiles(member_id) where deleted_at is null;
create unique index udx_crawled_profiles_url on crawled_profiles(url) where deleted_at is null;

create table crawled_profile_trades (
    profile_id bigint not null references crawled_profiles(id),
    trade varchar(255)
);

create table crawled_tasks (
    id bigint generated by default as identity,
    company varchar(255),
    address varchar(255),
    trade varchar(255),
    start_date date,
    end_date date,
    duration varchar(255),
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table crawled_posts (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    task_id bigint references crawled_tasks(id),
    title varchar(255),
    content TEXT,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table crawled_post_images (
    post_id bigint not null references crawled_posts(id),
    seq integer not null,
    url TEXT
);

create table crawled_credentials (
    id bigint generated by default as identity,
    member_id bigint not null references crawled_members(id),
    type varchar(255) not null,
    name varchar(255) not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table device_tokens (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    token varchar(1024) not null unique,
    platform varchar(255) not null,
    endpoint varchar(512) not null,
    enabled boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    primary key (id)
);

create table notifications (
    id bigint generated by default as identity,
    member_id bigint not null references members(id),
    type varchar(255) not null,
    sender_type varchar(255),
    sender_id bigint,
    reference_type varchar(255),
    reference_id bigint,
    read boolean not null,
    created_at timestamptz not null,
    modified_at timestamptz not null,
    deleted_at timestamptz,
    primary key (id)
);

create table kiscon_registration (
    ncr_gs_seq bigint not null,
    ncr_master_num text not null,
    ncr_gs_kname text not null,
    normalized_company_name text not null,
    ncr_gs_master text not null,
    ncr_item_name text not null,
    ncr_itemregno text not null,
    ncr_gs_addr text not null,
    ncr_area_name text not null,
    ncr_area_detail_name text not null,
    ncr_gs_date integer not null,
    ncr_gs_regdate integer not null,
    ncr_gs_flag text not null,
    ncr_off_tel text not null,
    ncr_gs_number text not null,
    ncr_gs_reason text not null,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index idx_kiscon_reg_master_num on kiscon_registration(ncr_master_num);
create index idx_kiscon_reg_normalized_name on kiscon_registration(normalized_company_name);

create table kiscon_admin_penalty (
    ncr_gs_seq bigint not null,
    ncr_master_num text not null,
    ncr_admi_kname text,
    normalized_company_name text,
    ncr_admi_master text,
    ncr_item_name text not null,
    ncr_itemregno text not null,
    ncr_admi_addr text,
    ncr_area_name text not null,
    ncr_area_detail_name text not null,
    ncr_admi_dename text,
    ecode_admi_con text,
    ncr_admi_reason text,
    ecode_admi_ground text,
    ncr_admi_fine bigint,
    ncr_admi_penalty bigint,
    ncr_admi_stop_sdate text,
    ncr_admi_stop_edate text,
    ncr_admi_canceldate text,
    ncr_admi_correct text,
    ncr_gs_date integer not null,
    ncr_gs_regdate integer not null,
    ncr_gs_flag text not null,
    ncr_off_tel text not null,
    ncr_pd_status text,
    ncr_gs_number text not null,
    ncr_gs_reason text not null,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index idx_kiscon_admi_master_num on kiscon_admin_penalty(ncr_master_num);
create index idx_kiscon_admi_normalized_name on kiscon_admin_penalty(normalized_company_name);

create table kiscon_arrears (
    id bigint generated by default as identity,
    seq_no text not null,
    company_name text not null,
    normalized_company_name text not null,
    address text not null,
    representative text not null,
    representative_age text not null,
    representative_address text,
    penalty_history text not null,
    penalty_dates text not null,
    arrears_amount text not null,
    publication_period text not null,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table kiscon_subcon_limits (
    id bigint generated by default as identity,
    seq_no text not null,
    violation_type text not null,
    company_name text not null,
    normalized_company_name text not null,
    corp_no text,
    biz_reg_no text not null,
    representative text not null,
    restriction_start text not null,
    restriction_end text not null,
    category text not null,
    announcement_date text not null,
    certificate_url text,
    note text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
create index idx_kiscon_subcon_biz_no on kiscon_subcon_limits(biz_reg_no);
create index idx_kiscon_subcon_normalized_name on kiscon_subcon_limits(normalized_company_name);

create table moel_wage_defaults (
    id bigint generated by default as identity,
    period text not null,
    name text not null,
    age text not null,
    company_name text not null,
    normalized_company_name text not null,
    industry text not null,
    personal_address text not null,
    company_address text not null,
    arrears_amount text not null,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table ecic_electrical_licenses (
    id bigint generated by default as identity,
    registration_no text not null,
    company_name text not null,
    normalized_company_name text not null,
    representative text not null,
    address text not null,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table cwma_retirement_fund (
    id bigint generated by default as identity,
    seq_no integer not null,
    project_name text not null,
    total_amount numeric not null,
    start_date date not null,
    end_date date not null,
    company_name text not null,
    normalized_company_name text not null,
    client_org text not null,
    address text not null,
    synced_at timestamptz not null default now(),
    primary key (id)
);
create index idx_cwma_normalized_name on cwma_retirement_fund(normalized_company_name);

create table feia_fire_licenses (
    id bigint generated by default as identity,
    seq_no integer not null,
    company_name text not null,
    normalized_company_name text not null,
    ceo_name text,
    address text not null,
    business_type text not null,
    license_div text not null,
    postal_code text not null,
    phone text,
    region text not null,
    region_detail text not null,
    synced_at timestamptz not null default now(),
    primary key (id)
);
