create table if not exists kiscon_registration (
    ncr_gs_seq bigint,
    biz_reg_no text not null,
    company_name text,
    representative text,
    trade_name text,
    trade_reg_no text,
    address text,
    region text,
    region_detail text,
    reg_date integer,
    announce_date integer,
    flag text,
    phone text,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_reg_biz_no on kiscon_registration(biz_reg_no);

create table if not exists kiscon_admin_penalty (
    ncr_gs_seq bigint,
    biz_reg_no text not null,
    company_name text,
    representative text,
    trade_name text,
    trade_reg_no text,
    address text,
    region text,
    region_detail text,
    penalty_type text,
    violation_content text,
    violation_detail text,
    penalty_ground text,
    fine_amount bigint default 0,
    penalty_amount bigint default 0,
    stop_start_date text,
    stop_end_date text,
    cancel_date text,
    correction text,
    penalty_date integer,
    announce_date integer,
    flag text,
    phone text,
    has_injunction text,
    synced_at timestamptz not null default now(),
    primary key (ncr_gs_seq)
);
create index if not exists idx_kiscon_admi_biz_no on kiscon_admin_penalty(biz_reg_no);

create table if not exists kiscon_arrears (
    id bigint generated by default as identity,
    company_name text not null,
    address text,
    representative text,
    penalty_history text,
    arrears_amount text,
    publication_period text,
    synced_at timestamptz not null default now(),
    primary key (id)
);

create table if not exists kiscon_subcon_limits (
    id bigint generated by default as identity,
    violation_type text,
    company_name text not null,
    corp_no text,
    biz_reg_no text not null,
    representative text,
    restriction_start text,
    restriction_end text,
    category text,
    announcement_date text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
create index if not exists idx_kiscon_subcon_biz_no on kiscon_subcon_limits(biz_reg_no);

create table if not exists cwma_retirement_fund (
    id bigint generated by default as identity,
    normalized_company_name text,
    company_name text,
    project_name text,
    total_amount bigint,
    start_date text,
    end_date text,
    client_org text,
    address text,
    primary key (id)
);
create index if not exists idx_cwma_retirement_normalized on cwma_retirement_fund(normalized_company_name);

create table if not exists moel_wage_defaults (
    id bigint generated by default as identity,
    period text,
    name text,
    age text,
    company_name text,
    industry text,
    personal_address text,
    company_address text,
    arrears_amount text,
    synced_at timestamptz not null default now(),
    primary key (id)
);
