package so.morton.api.storage.value;

public enum CredentialType {

    // 사업자 및 면허
    IDENTITY_VERIFICATION,
    SOLE_PROPRIETOR,
    CONSTRUCTION_LICENSE,
    SPECIALTY_CONSTRUCTION_LICENSE,
    // 증명서
    CAREER_CERTIFICATE,
    SKILL_GRADE_CERTIFICATE,
    OTHER_CERTIFICATE,
    // 자격증
    NATIONAL_TECHNICAL_QUALIFICATION,
    SKILLED_TECHNICIAN,
    OTHER_QUALIFICATION;
}
