// TODO: API 연동 후 제거 — 발표용 mock 데이터
const MOCK_TIMESTAMP = '2026-01-01T00:00:00Z'
export const MOCK_CREDENTIALS = [
  {
    id: 1,
    profileId: 1,
    type: 'IDENTITY_VERIFICATION' as const,
    status: 'ACCEPTED' as const,
    expiredAt: undefined,
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
  {
    id: 2,
    profileId: 1,
    type: 'SOLE_PROPRIETOR' as const,
    status: 'ACCEPTED' as const,
    expiredAt: '2026-09-21',
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
  {
    id: 3,
    profileId: 1,
    type: 'SPECIALTY_CONSTRUCTION_LICENSE' as const,
    status: 'ACCEPTED' as const,
    expiredAt: '2027-09-21',
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
  {
    id: 4,
    profileId: 1,
    type: 'CAREER_CERTIFICATE' as const,
    status: 'ACCEPTED' as const,
    expiredAt: undefined,
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
  {
    id: 5,
    profileId: 1,
    type: 'SKILL_GRADE_CERTIFICATE' as const,
    status: 'ACCEPTED' as const,
    expiredAt: '2027-02-18',
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
  {
    id: 6,
    profileId: 1,
    type: 'NATIONAL_TECHNICAL_QUALIFICATION' as const,
    status: 'ACCEPTED' as const,
    expiredAt: '2026-02-18',
    createdAt: MOCK_TIMESTAMP,
    modifiedAt: MOCK_TIMESTAMP,
  },
]
