// 고용노동부 체불사업주 명단 크롤링 → moel_wage_defaults (전체 교체)

import * as cheerio from 'cheerio'
import { createDb, insertBatched, notifySlack, runSync } from './lib'

const MOEL_DEFAULTER_URL = 'https://moel.go.kr/info/defaulter/defaulterList.do'
const PAGE_UNIT = 100
const EXPECTED_HEADERS = ['구분', '성명', '나이', '사업장명', '업종']

const sql = createDb()

interface MoelDefaulterItem {
  period: string
  name: string
  age: string
  companyName: string
  industry: string
  personalAddress: string
  companyAddress: string
  arrearsAmount: string
}

async function ensureTables(): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS moel_wage_defaults (
      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      period           TEXT,
      name             TEXT,
      age              TEXT,
      company_name     TEXT,
      industry         TEXT,
      personal_address TEXT,
      company_address  TEXT,
      arrears_amount   TEXT,
      synced_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `
}

async function fetchPage(pageIndex: number): Promise<string> {
  const response = await fetch(MOEL_DEFAULTER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      pageIndex: String(pageIndex),
      pageUnit: String(PAGE_UNIT),
    }).toString(),
    signal: AbortSignal.timeout(15_000),
  })

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} from MOEL defaulter page`)
  }

  return response.text()
}

function parseHtml(html: string): MoelDefaulterItem[] {
  const $ = cheerio.load(html)

  // 헤더 검증 — 사이트 구조 변경 감지
  const headers = $('table thead th')
    .map((_i, th) => $(th).text().trim())
    .get()
  if (!EXPECTED_HEADERS.every((h) => headers.some((actual) => actual.includes(h)))) {
    throw new Error(`MOEL defaulter table schema changed: ${headers.join(', ')}`)
  }

  const items: MoelDefaulterItem[] = []
  $('table tbody tr').each((_i, row) => {
    const cells = $(row).find('td')
    if (cells.length < 8) return
    items.push({
      period: $(cells[0]).text().trim(),
      name: $(cells[1]).text().trim(),
      age: $(cells[2]).text().trim(),
      companyName: $(cells[3]).text().trim(),
      industry: $(cells[4]).text().trim(),
      personalAddress: $(cells[5]).text().trim(),
      companyAddress: $(cells[6]).text().trim(),
      arrearsAmount: $(cells[7]).text().trim(),
    })
  })
  return items
}

async function fetchAll(): Promise<MoelDefaulterItem[]> {
  const all: MoelDefaulterItem[] = []
  for (let page = 1; ; page++) {
    const items = parseHtml(await fetchPage(page))
    all.push(...items)
    console.log(`[moel-sync]   page ${page}: ${items.length}건 (누적 ${all.length})`)
    if (items.length < PAGE_UNIT) break // 마지막 페이지
  }
  return all
}

async function main() {
  await ensureTables()

  console.log('[moel-sync] 체불사업주 명단 크롤링...')
  const items = await fetchAll()
  console.log(`[moel-sync] 총 ${items.length}건 수집`)

  await sql.begin(async (tx) => {
    await tx`DELETE FROM moel_wage_defaults`
    await insertBatched(
      tx,
      'moel_wage_defaults',
      items.map((item) => ({
        period: item.period,
        name: item.name,
        age: item.age,
        company_name: item.companyName,
        industry: item.industry,
        personal_address: item.personalAddress,
        company_address: item.companyAddress,
        arrears_amount: item.arrearsAmount,
      }))
    )
    console.log(`[moel-sync] moel_wage_defaults: ${items.length}건 저장`)
  })

  const summary = `✅ *MOEL 동기화 완료*\n체불사업주: ${items.length}건`
  console.log(`[moel-sync] ${summary}`)
  await notifySlack(summary)
}

runSync('moel-sync', sql, main)
