spring:
  application:
    name: api

  profiles:
    default: local

  jpa:
    open-in-view: false

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  flyway:
    enabled: false

  # TODO: aws
  # cloud:
  #   aws:
  #     region:
  #       static: ${AWS_REGION}
  #     credentials:
  #       access-key: ${AWS_ACCESS_KEY_ID}
  #       secret-key: ${AWS_SECRET_ACCESS_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    enable:
      process: false
      system: false

app:
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
    allowed-origin-patterns:
      - https://morton-career*.vercel.app
      - https://morton-plan*.vercel.app
      - https://*.bconnect.to

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 1h
    refresh-token-expiration: 7d

  sms:
    api-key: ${SOLAPI_API_KEY:}
    api-secret: ${SOLAPI_API_SECRET:}
    sender-number: ${SOLAPI_SENDER_NUMBER:}
