spring:
  application:
    name: api

management:
  metrics:
    enable:
      process: false
      system: false

app:
  database-url: ${DATABASE_URL:}
  database-username: ${DATABASE_USERNAME:}
  database-password: ${DATABASE_PASSWORD:}
  aws-access-key-id: ${AWS_ACCESS_KEY_ID:}
  aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  aws-region: ${AWS_REGION:}
  aws-s3-bucket: ${AWS_S3_BUCKET:}
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
    allowed-origin-patterns:
      - https://morton-career*.vercel.app
      - https://morton-plan*.vercel.app
