spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: never

app:
  jwt:
    secret: test-secret-key-for-jwt-authentication-minimum-256-bits