drop table if exists post_images cascade;
drop table if exists profile_trades cascade;
drop table if exists task_trades cascade;
drop table if exists messages cascade;
drop table if exists participants cascade;
drop table if exists posts cascade;
drop table if exists profiles cascade;
drop table if exists sessions cascade;
drop table if exists otps cascade;
drop table if exists tasks cascade;
drop table if exists members cascade;
drop table if exists chats cascade;

create table chats (
    id bigint generated by default as identity,
    title varchar(255) not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table members (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    name varchar(255) not null,
    phone varchar(11) not null unique,
    picture varchar(255) not null,
    role varchar(255) not null check ((role in ('GUEST','CLIENT','ARCHITECT','CONTRACTOR','FOREMAN','SKILLED','SEMI_SKILLED','HELPER','ADMIN'))),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table otps (
    id bigint generated by default as identity,
    phone varchar(11) not null,
    code varchar(6) not null,
    code_expired_at timestamp(6) not null,
    daily_count integer not null,
    attempt_count integer not null,
    signup_token varchar(255),
    signup_token_expired_at timestamp(6),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table sessions (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    agent varchar(255) not null,
    ip varchar(255) not null,
    refresh_token varchar(255) not null,
    revoked boolean not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table tasks (
    id bigint generated by default as identity,
    company varchar(255) not null,
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    task_title varchar(255) not null,
    event_title varchar(255) not null,
    start_date date not null,
    end_date date not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table messages (
    id bigint generated by default as identity,
    chat_id bigint not null references chats(id),
    sender_id bigint not null references members(id),
    content TEXT not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table participants (
    id bigint generated by default as identity,
    chat_id bigint not null references chats(id),
    member_id bigint not null references members(id),
    last_idx bigint not null,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table posts (
    id bigint generated by default as identity,
    author_id bigint references members(id),
    task_id bigint references tasks(id),
    content TEXT,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    member_id bigint not null unique references members(id),
    primary_trade varchar(255) not null check ((primary_trade in ('DESIGN','DEMOLITION','ELECTRICAL','PLUMBING','MECHANICAL','MASONRY','CARPENTRY','GLAZING','WATERPROOFING','PLASTERING','INSULATION','TILING','GROUTING','PAINTING','WALLPAPER','FILM_SHEET','HARDWOOD','VINYL','SINK','FURNITURE','AIR_CONDITIONING','HOISTING','TRANSPORT','CLEANING','GENERAL_LABOR'))),
    experience integer not null,
    headline varchar(255),
    about TEXT,
    zipcode varchar(5),
    city varchar(255),
    state varchar(255),
    street varchar(255),
    detail varchar(255),
    latitude numeric(10,7),
    longitude numeric(10,7),
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    deleted boolean default false not null,
    status varchar(255) check ((status in ('ACTIVE','DELETED'))),
    primary key (id)
);

create table post_images (
    post_id bigint not null references posts(id),
    images varchar(255)
);

create table profile_trades (
    profile_id bigint not null references profiles(id),
    trade varchar(255) check ((trade in ('DESIGN','DEMOLITION','ELECTRICAL','PLUMBING','MECHANICAL','MASONRY','CARPENTRY','GLAZING','WATERPROOFING','PLASTERING','INSULATION','TILING','GROUTING','PAINTING','WALLPAPER','FILM_SHEET','HARDWOOD','VINYL','SINK','FURNITURE','AIR_CONDITIONING','HOISTING','TRANSPORT','CLEANING','GENERAL_LABOR')))
);

create table task_trades (
    task_id bigint not null references tasks(id),
    trade varchar(255) check ((trade in ('DESIGN','DEMOLITION','ELECTRICAL','PLUMBING','MECHANICAL','MASONRY','CARPENTRY','GLAZING','WATERPROOFING','PLASTERING','INSULATION','TILING','GROUTING','PAINTING','WALLPAPER','FILM_SHEET','HARDWOOD','VINYL','SINK','FURNITURE','AIR_CONDITIONING','HOISTING','TRANSPORT','CLEANING','GENERAL_LABOR')))
);
